version: 2

sources:
  - name: raw
    database: northwind
    schema: public
    tables:
      - name: order_details
      - name: orders
      - name: products
      - name: customers
      - name: categories

models:
  - name: stg_order_details
    description: "Tabela staging dos detalhes dos pedidos"
    columns:
      - name: order_id
        description: "ID do pedido"
        tests:
          - not_null
      - name: product_id
        description: "ID do produto vendido"
        tests:
          - not_null
      - name: total_price
        description: "Valor total do item no pedido"
        tests:
          - not_null
          - positive_values

  - name: stg_orders
    description: "Tabela staging dos pedidos"
    columns:
      - name: order_id
        description: "ID do pedido"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "ID do cliente"
        tests:
          - not_null
      - name: order_date
        description: "Data em que o pedido foi realizado"
        tests:
          - not_null
      - name: shipped_date
        description: "Data em que o pedido foi enviado"
      - name: is_shipped
        description: "1 se foi enviado, 0 se não foi"

  - name: stg_products
    description: "Tabela staging dos produtos"
    columns:
      - name: product_id
        description: "ID do produto"
        tests:
          - unique
          - not_null
      - name: product_name
        description: "Nome do produto"

  - name: stg_customers
    description: "Tabela staging dos clientes"
    columns:
      - name: customer_id
        description: "ID do cliente"
        tests:
          - unique
          - not_null
      - name: region
        description: "Região do cliente"

  - name: stg_categories
    description: "Tabela staging das categorias"
    columns:
      - name: category_id
        description: "ID da categoria"
        tests:
          - unique
          - not_null
      - name: category_name
        description: "Nome da categoria"


